use anyhow::{Result, ensure};
use base64::{Engine, engine::general_purpose::STANDARD as B64};
use portable_pty::PtySize;
use std::{
    io::Read,
    sync::{Arc, mpsc},
    thread,
    time::Duration,
};
use terminator_core::*;

use super::shared::{Disconnect, Shared, relock};
use crate::presence;

/// Drain the notification waker socketpair after `poll` reports it readable.
/// The read end is non-blocking, so this stops at the first `WouldBlock`.
pub(crate) fn drain_wake(stream: &mut transport::Stream) {
    let mut buf = [0u8; 64];
    while let Ok(read) = stream.read(&mut buf) {
        if read == 0 {
            break;
        }
    }
}

pub(crate) fn serve(mut stream: transport::Stream, shared: Arc<Shared>) -> Result<()> {
    stream.set_nonblocking(false)?;
    stream.set_read_timeout(Some(Duration::from_secs(3)))?;
    stream.set_write_timeout(Some(Duration::from_secs(3)))?;
    let env: Envelope = read_frame(&mut stream)?;
    ensure!(
        env.version == PROTOCOL_VERSION,
        "Unsupported protocol version"
    );
    let authenticated = if env.auth == shared.auth {
        true
    } else {
        match &env.request {
            Request::Hook(e) => shared
                .runtime(&e.terminal_session_id)
                .is_ok_and(|r| relock(&r).token == env.auth),
            Request::ShellCommand { session }
            | Request::ShellPrompt { session, .. }
            | Request::Cwd { session, .. }
            | Request::TerminalNotify { session, .. } => shared
                .runtime(session)
                .is_ok_and(|r| relock(&r).token == env.auth),
            _ => false,
        }
    };
    ensure!(authenticated, "Authentication failed");
    if matches!(env.request, Request::Snapshot) {
        let executable = std::env::current_exe().ok();
        let helper = &shared.helper.executable;
        let available = executable_available(helper);
        let mut state = relock(&shared.state);
        if state.daemon_executable != executable
            || state.attachment_helper_executable.as_ref() != Some(helper)
            || state.attachment_helper_available != Some(available)
        {
            state.daemon_executable = executable;
            state.attachment_helper_executable = Some(helper.clone());
            state.attachment_helper_available = Some(available);
            state.revision = state.revision.saturating_add(1);
        }
        presence::expire_observations(&mut state, now());
        if let Some(hint) = &env.snapshot_hint
            && hint == &state.snapshot_hint()
        {
            write_frame(&mut stream, &Response::Unchanged)?;
            return Ok(());
        }
    }
    if let Request::Attach {
        session,
        rows,
        cols,
    } = env.request
    {
        let _disconnect = Disconnect(stream.try_clone()?);
        ensure!(
            rows > 0 && cols > 0 && rows <= 500 && cols <= 1000,
            "Invalid terminal dimensions"
        );
        let rt = shared.runtime(&session)?;
        let (tx, rx) = mpsc::sync_channel(128);
        {
            let mut r = relock(&rt);
            r.master.resize(PtySize {
                rows,
                cols,
                pixel_width: 0,
                pixel_height: 0,
            })?;
            r.parser.screen_mut().set_size(rows, cols);
            // Formatted screen is generated by vt100, never replay arbitrary OSC effects.
            let mut snapshot = Vec::new();
            let mut history = r.parser.screen().clone();
            history.set_scrollback(10_000);
            for offset in (1..=history.scrollback()).rev() {
                history.set_scrollback(offset);
                if let Some(row) = history.rows(0, cols).next() {
                    snapshot.extend_from_slice(row.as_bytes());
                    snapshot.extend_from_slice(b"\r\n");
                }
            }
            if r.parser.screen().alternate_screen() {
                snapshot.extend_from_slice(b"\x1b[?1049h");
            }
            snapshot.extend(r.parser.screen().state_formatted());
            snapshot.extend(r.parser.callbacks().modes_formatted());
            write_frame(&mut stream, &Response::Data(B64.encode(snapshot)))?;
            r.subscribers.push(tx);
        }
        stream.set_read_timeout(None)?;
        let mut input = stream.try_clone()?;
        let input_disconnect = Disconnect(input.try_clone()?);
        let input_rt = Arc::clone(&rt);
        let input_shared = Arc::clone(&shared);
        let session_id = session.clone();
        thread::spawn(move || {
            // Same containment as the connection thread: input handling
            // must never take the daemon down with a misbehaving client.
            let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                let _disconnect = input_disconnect;
                while let Ok(req) = read_frame::<Request>(&mut input) {
                    match req {
                        Request::Input { data } => {
                            if let Ok(bytes) = B64.decode(data)
                                && input_shared.forward_input(&input_rt, &bytes).is_err()
                            {
                                break;
                            }
                        }
                        Request::Resize { rows, cols }
                            if rows > 0 && cols > 0 && rows <= 500 && cols <= 1000 =>
                        {
                            let mut r = relock(&input_rt);
                            let _ = r.master.resize(PtySize {
                                rows,
                                cols,
                                pixel_width: 0,
                                pixel_height: 0,
                            });
                            r.parser.screen_mut().set_size(rows, cols);
                            drop(r);
                            let mut s = relock(&input_shared.state);
                            if let Some(rec) = s.sessions.iter_mut().find(|s| s.id == session_id) {
                                rec.rows = rows;
                                rec.cols = cols;
                            }
                        }
                        _ => break,
                    }
                }
            }));
        });
        while let Ok(frame) = rx.recv_timeout(Duration::from_secs(2)) {
            write_frame(&mut stream, &frame)?;
            if matches!(frame, Response::End) {
                break;
            }
        }
        // A quiet terminal must not time out: keep the stream alive until it disconnects or ends.
        if !relock(&rt).ended {
            loop {
                match rx.recv_timeout(Duration::from_secs(2)) {
                    Ok(frame) => {
                        write_frame(&mut stream, &frame)?;
                        if matches!(frame, Response::End) {
                            break;
                        }
                    }
                    Err(mpsc::RecvTimeoutError::Timeout) => {
                        write_frame(&mut stream, &Response::Ok)?;
                    }
                    Err(_) => break,
                }
            }
        }
        Ok(())
    } else {
        let response = shared
            .handle(env.request)
            .unwrap_or_else(|e| Response::Error(format!("{e:#}")));
        snapshot::write_response(&mut stream, &response, env.snapshot_chunks)
    }
}
